# Generated by Django 4.1.3 on 2022-11-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.CharField(max_length=12, verbose_name='Número registro')),
                ('nome', models.CharField(max_length=50)),
                ('sede_empresarial', models.CharField(max_length=50, verbose_name='Sede empresarial')),
                ('setor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Demissoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.CharField(max_length=50, verbose_name='Número registro')),
                ('nome', models.CharField(max_length=50)),
                ('sede_empresarial', models.CharField(max_length=50, verbose_name='Sede empresarial')),
                ('setor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.CharField(max_length=12, verbose_name='Número registro')),
                ('nome', models.CharField(max_length=50)),
                ('sede_empresarial', models.CharField(max_length=50, verbose_name='Sede empresarial')),
                ('setor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.CharField(max_length=12, verbose_name='Número registro')),
                ('nome', models.CharField(max_length=50)),
                ('sede_empresarial', models.CharField(max_length=50, verbose_name='Sede empresarial')),
                ('setor', models.CharField(max_length=50)),
            ],
        ),
    ]
